#pragma once

#include "WCMacros.hpp"

WC_BEGIN_NAMESPACE
WC_AST_BEGIN_NAMESPACE

class AddExprAdd;
class AddExprBOr;
class AddExprBXor;
class AddExprNoOp;
class AddExprSub;
class AddExprTwoOps;
class ArrayLit;
class ArrayLitExprs;
class ArrayLitExprsMulti;
class ArrayLitExprsSingle;
class AssertStmnt;
class AssignExprAssign;
class AssignExprAssignAdd;
class AssignExprAssignARShift;
class AssignExprAssignBAnd;
class AssignExprAssignBase;
class AssignExprAssignBOr;
class AssignExprAssignBXor;
class AssignExprAssignDiv;
class AssignExprAssignLRShift;
class AssignExprAssignLShift;
class AssignExprAssignMod;
class AssignExprAssignMul;
class AssignExprAssignSub;
class AssignExprBinaryOpBase;
class AssignExprNoAssign;
class BoolLit;
class BreakStmntNoCond;
class BreakStmntWithCond;
class CastExprCast;
class CastExprNoCast;
class CmpExprEQ;
class CmpExprGE;
class CmpExprGT;
class CmpExprLE;
class CmpExprLT;
class CmpExprNE;
class CmpExprNoOp;
class CmpExprTwoOps;
class DeclDefFunc;
class DeclDefVarDecl;
class Func;
class FuncArg;
class FuncArgListMulti;
class FuncArgListSingle;
class FuncCall;
class FuncCallArgListMulti;
class FuncCallArgListSingle;
class Identifier;
class IfStmntElse;
class IfStmntElseIf;
class IfStmntNoElse;
class IntLit;
class LAndExprAnd;
class LAndExprNoOp;
class LoopStmntNoCond;
class LoopStmntWithCond;
class LOrExprNoOp;
class LOrExprOr;
class Module;
class MulExprBAnd;
class MulExprDiv;
class MulExprMod;
class MulExprMul;
class MulExprNoOp;
class MulExprTwoOps;
class NextStmntNoCond;
class NextStmntWithCond;
class NoOpStmnt;
class NotExprBNot;
class NotExprLNot;
class NotExprNoOp;
class PostfixExprArrayLookup;
class PostfixExprDec;
class PostfixExprFuncCall;
class PostfixExprInc;
class PostfixExprIncDecBase;
class PostfixExprNoPostfix;
class PrimaryExprArrayLit;
class PrimaryExprBoolLit;
class PrimaryExprIdentifier;
class PrimaryExprIntLit;
class PrimaryExprRandExpr;
class PrimaryExprReadnum;
class PrimaryExprStrLit;
class PrimaryExprTime;
class PrimitiveType;
class PrintStmnt;
class RandExprRand;
class RandExprSRand;
class ReadnumExpr;
class ReturnStmntNoCondVoid;
class ReturnStmntNoCondWithValue;
class ReturnStmntWithCondAndValue;
class ReturnStmntWithCondBase;
class ReturnStmntWithCondVoid;
class Scope;
class ScopeStmnt;
class ShiftExprARShift;
class ShiftExprLRShift;
class ShiftExprLShift;
class ShiftExprNoOp;
class ShiftExprTwoOps;
class StmntAssertStmnt;
class StmntAssignExpr;
class StmntBreakStmnt;
class StmntIfStmnt;
class StmntLoopStmnt;
class StmntNextStmnt;
class StmntNoOpStmnt;
class StmntPrintStmnt;
class StmntReturnStmnt;
class StmntScopeStmnt;
class StmntVarDecl;
class StmntWhileStmnt;
class StrLit;
class TernaryExprNoCond;
class TernaryExprWithCond;
class TimeExpr;
class TypeArray;
class TypePrimitive;
class UnaryExprMinus;
class UnaryExprParen;
class UnaryExprPlus;
class UnaryExprPlusMinusBase;
class UnaryExprPrimary;
class VarDeclExplicitType;
class VarDeclInferType;
class WhileStmnt;

/* Interface for a visitor to AST nodes */
class ASTNodeVisitor {
public:
    virtual ~ASTNodeVisitor() = default;
    
    virtual void visit(const AddExprAdd & node) = 0;
    virtual void visit(const AddExprBOr & node) = 0;
    virtual void visit(const AddExprBXor & node) = 0;
    virtual void visit(const AddExprNoOp & node) = 0;
    virtual void visit(const AddExprSub & node) = 0;
    virtual void visit(const AddExprTwoOps & node) = 0;
    virtual void visit(const ArrayLit & node) = 0;
    virtual void visit(const ArrayLitExprs & node) = 0;
    virtual void visit(const ArrayLitExprsMulti & node) = 0;
    virtual void visit(const ArrayLitExprsSingle & node) = 0;
    virtual void visit(const AssertStmnt & node) = 0;
    virtual void visit(const AssignExprAssign & node) = 0;
    virtual void visit(const AssignExprAssignAdd & node) = 0;
    virtual void visit(const AssignExprAssignARShift & node) = 0;
    virtual void visit(const AssignExprAssignBAnd & node) = 0;
    virtual void visit(const AssignExprAssignBase & node) = 0;
    virtual void visit(const AssignExprAssignBOr & node) = 0;
    virtual void visit(const AssignExprAssignBXor & node) = 0;
    virtual void visit(const AssignExprAssignDiv & node) = 0;
    virtual void visit(const AssignExprAssignLRShift & node) = 0;
    virtual void visit(const AssignExprAssignLShift & node) = 0;
    virtual void visit(const AssignExprAssignMod & node) = 0;
    virtual void visit(const AssignExprAssignMul & node) = 0;
    virtual void visit(const AssignExprAssignSub & node) = 0;
    virtual void visit(const AssignExprBinaryOpBase & node) = 0;
    virtual void visit(const AssignExprNoAssign & node) = 0;
    virtual void visit(const BoolLit & node) = 0;
    virtual void visit(const BreakStmntNoCond & node) = 0;
    virtual void visit(const BreakStmntWithCond & node) = 0;
    virtual void visit(const CastExprCast & node) = 0;
    virtual void visit(const CastExprNoCast & node) = 0;
    virtual void visit(const CmpExprEQ & node) = 0;
    virtual void visit(const CmpExprGE & node) = 0;
    virtual void visit(const CmpExprGT & node) = 0;
    virtual void visit(const CmpExprLE & node) = 0;
    virtual void visit(const CmpExprLT & node) = 0;
    virtual void visit(const CmpExprNE & node) = 0;
    virtual void visit(const CmpExprNoOp & node) = 0;
    virtual void visit(const CmpExprTwoOps & node) = 0;
    virtual void visit(const DeclDefFunc & node) = 0;
    virtual void visit(const DeclDefVarDecl & node) = 0;
    virtual void visit(const Func & node) = 0;
    virtual void visit(const FuncArg & node) = 0;
    virtual void visit(const FuncArgListMulti & node) = 0;
    virtual void visit(const FuncArgListSingle & node) = 0;
    virtual void visit(const FuncCall & node) = 0;
    virtual void visit(const FuncCallArgListMulti & node) = 0;
    virtual void visit(const FuncCallArgListSingle & node) = 0;
    virtual void visit(const Identifier & node) = 0;
    virtual void visit(const IfStmntElse & node) = 0;
    virtual void visit(const IfStmntElseIf & node) = 0;
    virtual void visit(const IfStmntNoElse & node) = 0;
    virtual void visit(const IntLit & node) = 0;
    virtual void visit(const LAndExprAnd & node) = 0;
    virtual void visit(const LAndExprNoOp & node) = 0;
    virtual void visit(const LoopStmntNoCond & node) = 0;
    virtual void visit(const LoopStmntWithCond & node) = 0;
    virtual void visit(const LOrExprNoOp & node) = 0;
    virtual void visit(const LOrExprOr & node) = 0;
    virtual void visit(const Module & node) = 0;
    virtual void visit(const MulExprBAnd & node) = 0;
    virtual void visit(const MulExprDiv & node) = 0;
    virtual void visit(const MulExprMod & node) = 0;
    virtual void visit(const MulExprMul & node) = 0;
    virtual void visit(const MulExprNoOp & node) = 0;
    virtual void visit(const MulExprTwoOps & node) = 0;
    virtual void visit(const NextStmntNoCond & node) = 0;
    virtual void visit(const NextStmntWithCond & node) = 0;
    virtual void visit(const NoOpStmnt & node) = 0;
    virtual void visit(const NotExprBNot & node) = 0;
    virtual void visit(const NotExprLNot & node) = 0;
    virtual void visit(const NotExprNoOp & node) = 0;
    virtual void visit(const PostfixExprArrayLookup & node) = 0;
    virtual void visit(const PostfixExprDec & node) = 0;
    virtual void visit(const PostfixExprFuncCall & node) = 0;
    virtual void visit(const PostfixExprInc & node) = 0;
    virtual void visit(const PostfixExprIncDecBase & node) = 0;
    virtual void visit(const PostfixExprNoPostfix & node) = 0;
    virtual void visit(const PrimaryExprArrayLit & node) = 0;
    virtual void visit(const PrimaryExprBoolLit & node) = 0;
    virtual void visit(const PrimaryExprIdentifier & node) = 0;
    virtual void visit(const PrimaryExprIntLit & node) = 0;
    virtual void visit(const PrimaryExprRandExpr & node) = 0;
    virtual void visit(const PrimaryExprReadnum & node) = 0;
    virtual void visit(const PrimaryExprStrLit & node) = 0;
    virtual void visit(const PrimaryExprTime & node) = 0;
    virtual void visit(const PrimitiveType & node) = 0;
    virtual void visit(const PrintStmnt & node) = 0;
    virtual void visit(const RandExprRand & node) = 0;
    virtual void visit(const RandExprSRand & node) = 0;
    virtual void visit(const ReadnumExpr & node) = 0;
    virtual void visit(const ReturnStmntNoCondVoid & node) = 0;
    virtual void visit(const ReturnStmntNoCondWithValue & node) = 0;
    virtual void visit(const ReturnStmntWithCondAndValue & node) = 0;
    virtual void visit(const ReturnStmntWithCondBase & node) = 0;
    virtual void visit(const ReturnStmntWithCondVoid & node) = 0;
    virtual void visit(const Scope & node) = 0;
    virtual void visit(const ScopeStmnt & node) = 0;
    virtual void visit(const ShiftExprARShift & node) = 0;
    virtual void visit(const ShiftExprLRShift & node) = 0;
    virtual void visit(const ShiftExprLShift & node) = 0;
    virtual void visit(const ShiftExprNoOp & node) = 0;
    virtual void visit(const ShiftExprTwoOps & node) = 0;
    virtual void visit(const StmntAssertStmnt & node) = 0;
    virtual void visit(const StmntAssignExpr & node) = 0;
    virtual void visit(const StmntBreakStmnt & node) = 0;
    virtual void visit(const StmntIfStmnt & node) = 0;
    virtual void visit(const StmntLoopStmnt & node) = 0;
    virtual void visit(const StmntNextStmnt & node) = 0;
    virtual void visit(const StmntNoOpStmnt & node) = 0;
    virtual void visit(const StmntPrintStmnt & node) = 0;
    virtual void visit(const StmntReturnStmnt & node) = 0;
    virtual void visit(const StmntScopeStmnt & node) = 0;
    virtual void visit(const StmntVarDecl & node) = 0;
    virtual void visit(const StmntWhileStmnt & node) = 0;
    virtual void visit(const StrLit & node) = 0;
    virtual void visit(const TernaryExprNoCond & node) = 0;
    virtual void visit(const TernaryExprWithCond & node) = 0;
    virtual void visit(const TimeExpr & node) = 0;
    virtual void visit(const TypeArray & node) = 0;
    virtual void visit(const TypePrimitive & node) = 0;
    virtual void visit(const UnaryExprMinus & node) = 0;
    virtual void visit(const UnaryExprParen & node) = 0;
    virtual void visit(const UnaryExprPlus & node) = 0;
    virtual void visit(const UnaryExprPlusMinusBase & node) = 0;
    virtual void visit(const UnaryExprPrimary & node) = 0;
    virtual void visit(const VarDeclExplicitType & node) = 0;
    virtual void visit(const VarDeclInferType & node) = 0;
    virtual void visit(const WhileStmnt & node) = 0;
};

WC_AST_END_NAMESPACE
WC_END_NAMESPACE
